### ISSUE TITLE
[Feature request] send a entity properties as payload

### ISSUE THREAD

**Issue by idealley** [graknlabs/grakn-node#2]
Following the discussion on slack I am proposing to add the following:

a typical insert call looks like this (I will post this part to the grakn repo too):
```
 insert $g isa person has firstname "Titus"; has identifier "Titus Groan"; has surname "Groan"; has gender "male";
commit
```
The `has` key word has (no pun intended) to be repeated for each `resource` added, followed by the `resource` `key` and `values`.

What if, when we have many properties to add, we could send it in the following way:

```insert $g isa person has
    {
       firstname: 'Titus',
       surname: 'Groan',
       identifier: `${firstname} ${surname}`
       gender: 'male'
    };
commit
```
Then in node we could simply send a string with out modifying the api as that string would just be forwarded to GRAKN

```js
graph.execute('insert $bob isa person; has { firstname: "Titus", surname: "Groan", identifier: "Titus Groan", gender: "male"').then((resp) => { console.log(resp); });
```
With string interpolation:

```js
const obj = {
  firstname: 'Titus',
  surname: 'Groan',
  age: 45
};

graph.execute(`
  insert $bob isa person; 
  has { 
    firstname: ${obj.firstname}, 
    surname: ${obj.surname}, 
    identifier: ${obj.firstname obj.surname}, 
    gender: ${obj.age}
`).then((resp) => { console.log(resp); });

```
Maybe not the most readable...

@marco-scoppetta proposed:
```
    graph.insert('$bob isa person').has(data).then();
```

Which makes it really readable. Would `has()` be able to parse either an object or a string?

```js
const obj = {
  firstname: 'Titus',
  surname: 'Groan',
  age: 45
}

const str = 'firstname "Titus"';
```
The string would read almost like the GRAQL API especially if we can chain many has... 

```js
   graph.insert('$bob isa person').has('firstname "Titus"').has('surname "Groan"').then();
```
But hey, I guess, then we would still write:

```js
   graph.insert('$bob isa person; has firstname "Titus"; has surname "Groan"').then();
```

The last solution I think of would be to change the function signature with an optional argument:

```js
    insert(string [, object])
```

Finally how do you prefer to iterate?

```js
 Object.keys(obj).map((key) => {
    console.log(key, obj[key]);
});

// with a dependency like loadash
_.map(_.mapValues(item, (v, k) => {
    console.log(v, k);
})

// or ramda
const log = (v, k) => {console.log(v, k)};
R.mapObjIndexed(log, obj);

// for loop?
...
```

Would you mind? to ES6fy the library and add a compilation step with webpack thus we could produce a nodejs and a browser output? as well as using all last features of js. 

We could also put it on travis? but then I have experience with travis, mocha, istanbul and coveralls... but not jest and cucumber, I guess I could learn ;)

Let me know what you think as I would be happy to assist. But I do not want to do a PR that reflects only my way of thinking...

**Comment by marco-scoppetta** [comment]
Hi @idealley ,
thanks for the useful feedback.

We are going to start implementing functionalities that help the developer to compose the query they want to execute in a more generic way.

So in the next coming releases you will be able to either `execute` a string with whatever Graql query you need (as it is now) or you will be able to compose the query with helper methods and pass objects or string to them. 

```
/* Example of match-insert query */

const attributes = { birth-date: "03-04-1980", city:"London", gender:"female" };

graph.match(var("p").has("identifier", "Mary Guthrie"))
        .insert(var("p").has(attributes).execute().then((resp)=>{...});

```

So some of the helper methods (e.g. `.has()`) could potentially accept different type of params.

Do not hesitate do give us more feedback on this if you have some.

I am not clear what do you mean on the second part of the question. 
You can iterate on the response in whatever way is more convenient to you in your app,
the `execute()` method only returns a Promise. Also the code is already using ES6 features, so I am not sure why you are asking to ES6fy it.
This is a Node app so you can use every JS feature you want without need to transpile it to vanilla JS, if you need it in a browser you can fork it add a `babel-env` dependency in your project.

Marco

**Comment by idealley** [comment]
Sorry to be unclear, I was thinking of reconstructing the string with the payload, not in my code. Thus I thought I could help and was asking if:

1. you would agree to use dependencies
2. if yes if you had any preference

then could I give you a hand? if so feel free to assign me some tasks

for the ES6 I saw that it uses ES6 features, but also that it could use more such as `class` or `imports` and `export` functions etc, `async` `await`...

To maximize compatibility, it would be best to compile...

Let me know!

Sam

**Comment by marco-scoppetta** [comment]
Hi @idealley .
in case you just want to build the string, without being generic, I think the fastest way would be to implement a quick helper function such as:

```
function serialiseAttributes(varname, attrs){
  return Object.keys(attrs).map(key => `$${varname} has ${key} "${obj[key]}";`)
              .reduce((str,attr)=>str+=attr,"");
}

// so that you can do:
const obj = {
  firstname: 'Titus',
  surname: 'Groan',
  age: 45
} 

graph.execute(`$x isa person; ${serialiseAttrs('x', obj)}`);
```
This is a quick solution and it does not require you to reconstruct the query in the code.
For the Node driver we would prefer to implement a more generic solution that allows the user to build the query in the code. At least for now. 

Let us know if you have other ideas or considerations

thank you!

Marco
